name: unstitched-zarr-env
channels:
 - conda-forge
 - nodefaults
dependencies:
 - python=3.12
 - numpy
 - scipy
 - dask
 - tifffile>=2023.9.26
 - zarr
 - matplotlib
 - tqdm
 - pip
 - pip:
   - git+https://github.com/fideus-labs/ngff-zarr.git@refs/pull/255/head#subdirectory=py